#!/usr/bin/python

import os
import sys 
import yaml

with open("docker-compose.yaml", "r") as stream:
    try:
        docker = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)

args = sys.argv
args.pop(0)
args = ' '.join(args)

container = docker['services']['server']['container_name']

os.system('docker container exec -it --user www-data ' + container + ' php /usr/share/nginx/html/artisan ' + args)